shamefullyHoist: true
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
onlyBuiltDependencies:
  - '@ladybugdb/core'
  - onnxruntime-node
  - protobufjs
  - sharp
  - tree-sitter
  - tree-sitter-javascript
  - tree-sitter-typescript
