shamefullyHoist: true
allowBuilds:
  '@ladybugdb/core': true
  '@scarf/scarf': false
  '@tree-sitter-grammars/tree-sitter-zig': false
  electron-winstaller: true
  electron: true
  esbuild: true
  gitnexus: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  tree-sitter-c-sharp: false
  tree-sitter-cpp: false
  tree-sitter-go: false
  tree-sitter-java: false
  tree-sitter-javascript: true
  tree-sitter-php: false
  tree-sitter-python: false
  tree-sitter-ruby: false
  tree-sitter-rust: false
  tree-sitter-typescript: true
  tree-sitter: true
  lefthook: true
