export const IpcChannel = {
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  settingsRemove: 'settings:remove',
  mediaListVolumes: 'media:list-volumes',
  mediaListFolder: 'media:list-folder',
  mediaReadExif: 'media:read-exif',
  albumsList: 'albums:list',
  albumsCreate: 'albums:create',
  albumsRename: 'albums:rename',
  albumsRemove: 'albums:remove',
  albumsAddPhoto: 'albums:add-photo',
  albumsMovePhoto: 'albums:move-photo',
  albumsRemovePhoto: 'albums:remove-photo',
  albumsRatePhoto: 'albums:rate-photo',
  albumsUpdatePrintConfig: 'albums:update-print-config',
  mediaRotateImage: 'media:rotate-image',
  menuOpenPreferences: 'menu:open-preferences',
  menuTogglePhotoFullscreen: 'menu:toggle-photo-fullscreen',
  menuRotatePhotoCw: 'menu:rotate-photo-cw',
  menuRotatePhotoCcw: 'menu:rotate-photo-ccw',
  windowSetFullScreen: 'window:set-full-screen',
  windowLeaveFullScreen: 'window:leave-full-screen'
} as const;
